### PR TITLE
Update to runtime 24.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
@lw64 merging this against branch/24.08 as this is more or less the same changes already present in beta.

I need it also to create the 24.08 branch of electron baseapp.

**Comment by bbhtt** [comment]
Switched the default branch as well.

**Comment by lw64** [comment]
Thank you a lot! I assume everything got set up by you, and right now I don't have to do anything anymore? (except merging updates in the future)

**Comment by bbhtt** [comment]
Yes you only have to merge future updates.

**Pull request closed without merging**
