### PR TITLE
Update runtime version to 23.08beta

### PR DESCRIPTION
**Pull request by alatiera**
- Update graphviz-5.0.0.tar.gz to 5.0.1
- Update vala-0.56.2.tar.xz to 0.56.3
- Update vala-0.56.2.tar.xz to 0.56.3
- Update graphviz-5.0.1.tar.gz to 6.0.1
- Change runtime to 22.08
- Update libgee-0.20.5.tar.xz to 0.20.6
- Add uncrustify
- Update libgee-0.20.5.tar.xz to 0.20.6
- Update 2 modules
- Remove unnecessary stuff
- Add patch to vls
- Update vls to specific commit
- Update 3 modules
- Don't run tests
- Update vala-language-server-0.48.5.tar.xz to 0.48.6
- Update vala-language-server-0.48.6.tar.xz to 0.48.7
- Update 3 modules
- Update vala-0.56.5.tar.xz to 0.56.6
- Update 3 modules
- Mark valac and vls as important and only update these
- Update runtime version to 23.08beta

### CODE REVIEW

**Comment by lw64** [comment]
Thanks @alatiera @bilelmoussaoui !

**Comment by Erick555** [comment]
@lw64 the CI for this failed, the change isn't available in flathub-beta repo.

**Comment by lw64** [comment]
I guess its because org.freedesktop.Sdk//23.08beta wasn't released yet.

**Comment by lw64** [comment]
bot, build org.freedesktop.Sdk.Extension.vala

**Comment by lw64** [comment]
What needs to be done for the CI to succeed?

**Comment by alatiera** [comment]
> I guess its because org.freedesktop.Sdk//23.08beta wasn't released yet.

Its there, but buildbot doesn't pick it up for some reason. Needs further debugging.

**Pull request merged**
